org: danielb
app: aws-redistribution
service: aws-redistribution
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x

constructs:
    jobs:
        type: queue
        worker:
            handler: dist/handler.consumer

functions:
    producer:
        handler: dist/handler.producer
        events:
            - httpApi:
                  method: post
                  path: /produce
        environment:
            QUEUE_URL: ${construct:jobs.queueUrl}

plugins:
    - serverless-lift
