org: danielb
app: aws-serverless
service: aws-serverless
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x

functions:
    hello:
        handler: dist/handler.handler
        events:
            - httpApi:
                  path: /
                  method: get
